# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"INPUT_DATA_DIR": "01_data_acquisition.ipynb",
         "INPUT_DATA_NAME": "01_data_acquisition.ipynb",
         "HOLD_OUT_DATA_NAME": "01_data_acquisition.ipynb",
         "compute": "01_data_acquisition.ipynb",
         "get_data": "01_data_acquisition.ipynb",
         "get_hold_out_data": "01_data_acquisition.ipynb",
         "test_get_data": "01_data_acquisition.ipynb",
         "test_get_holdout": "01_data_acquisition.ipynb"}

modules = ["config/default_config.py",
           "data_acquisition/main.py",
           "tests/all_tests.py",
           "data_processing/utils.py"]

doc_url = "https://Navaneeth.github.io/notebook-ml/"

git_url = "https://github.com/Navaneeth/notebook-ml/tree/master/"

def custom_doc_links(name): return None
