# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/init/002_tests.ipynb (unless otherwise specified).

__all__ = ['test_get_data', 'test_get_holdout']

# Comes from 01_data_acquisition.ipynb, cell
from altaml_template_repo.data_acquisition import *

def test_get_data():
    return True


def test_get_holdout():
    return True

assert test_get_holdout()
assert test_get_data()

# Cell

