# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/init/001_create_configs.ipynb (unless otherwise specified).

__all__ = ['INPUT_DATA_DIR', 'INPUT_DATA_NAME', 'HOLD_OUT_DATA_NAME', 'compute']

# Comes from 01_data_acquisition.ipynb, cell
from pathlib import Path

INPUT_DATA_DIR = Path.cwd().parents[0] / 'data'
INPUT_DATA_NAME = 'input_data_name.csv'
HOLD_OUT_DATA_NAME = 'hold_out_data.csv'
compute = 'local'

# Cell
